import { Box } from '@chakra-ui/layout';
import './globals.css'
import { Providers } from "./providers";
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['vietnamese'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Box maxWidth={'1280px'} margin={'auto'}>
            {children}
          </Box>
        </Providers>
      </body>
    </html>
  )
}
